#!/bin/bash

# meant to be run via systemd on a vbox minion
# an easier way to deploy since salt-cloud doesn't work

# get the new hostname
newHostName=$(VBoxControl --nologo guestproperty get GuestName | awk '{ print $2 }')

# make sure the result isn't zero length (indicating VBoxControl doesn't work), or "value" (not set)
if [ ${#newHostName} -eq 0 ]; then
  echo "vbox guest property not set - exiting."
  exit 255
elif [ "${newHostName}" == "value" ]; then
  echo "vbox guest property not set - exiting."
  exit 255
fi

# set the hostname
hostnamectl set-hostname ${newHostName}.lab

# statically set the hostname in Salt
echo ${newHostName}.lab > /etc/salt/minion_id

# point the minion at the right master
echo "master: 10.187.88.10" | tee /etc/salt/minion

# regenerate UUID, otherwise Ubuntu acts totally stupid
if [ -f /etc/machine-id ]; then
  # required for ubuntu 18.04
  rm -f /etc/machine-id && dbus-uuidgen --ensure=/etc/machine-id
fi

# regenerate the host SSH keys
ssh-keygen -A

# start Salt minion next boot
systemctl enable salt-minion

# get rid of the evidence
systemctl disable minion-setup
rm /etc/systemd/system/minion-setup.service
systemctl daemon-reload

# reboot after burying the body
(sleep 5; reboot &)&
rm -f ${0}

# fin
exit 0
